Problem Statement 1: 
Write a function so that the columns of the output matrix are powers of the input vector. 
The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 


In [17]:
import numpy as np#imported numpy and aliased as np
def power(x,N):
  #for every element in array we are performing power operation for N times
  s=np.column_stack([x**(N-i-1) for i in range(N)])#np.column_stack is used to convert 1d array to 2D array by concatinating arrays column wise
  print(s)
  print(type(s))

#Created an array using np.array
x=np.array([1,2,3,4,5])
N=5
power(x,N)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
<class 'numpy.ndarray'>


 Write a function to find moving average in an array over a window:  Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 

In [40]:
def average(l,n,k):
  a=[]
  for i in range(n-k+1):
    sum=0
    for j in range(k):
      sum=sum+l[i+j]
    sum=sum/k
    a.append(sum)
  a=np.array(a)
  print(a)

l=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n=13
k=3
average(l,n,k)

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
